RedHat-SP-Security/keylime-tests

TESTING.md
setup/install_upstream_keylime/test.sh

As the respective keylime issue has been fixed upstream already.

Remove cert timezone workaround

---

Library/test-helpers/lib.sh
Multihost/basic-attestation/test.sh
functional/basic-attestation-on-localhost/test.sh
functional/keylime_tenant-commands-on-localhost/test.sh

Use "set -m" every time so we are able to kill processes. 
At the same time use non-zero exit code when SIGINT was not enough
unless the coverage script is being used.

Make __limeStopKeylimeService more robust

---

Library/test-helpers/lib.sh
setup/configure_tpm_emulator/test.sh

RHEL-9 already contains swtpm so we do not need to use custom build of ibmswtpm2.

Replace ibmswtpm2 with swtpm on RHEL

---

Library/sync/lib.sh
Library/sync/main.fmf
Library/sync/runtest.sh
Library/sync/sync-block
Library/sync/sync-get.service
Library/sync/sync-set
Multihost/basic-attestation/test.sh

Implements Library/sync so that multihost tests can be run outside of Beaker/Restraint environment.

Add Library/sync and adjust multihost test for it

---

Library/test-helpers/lib.sh

Attachments are not available in Packit CI and therefore it is handy to see tail of a log when service cannot be stopped.

Improve logging when service stop failed

---

Multihost/basic-attestation/main.fmf
Multihost/basic-attestation/payload/action_list
Multihost/basic-attestation/payload/autorun.sh
Multihost/basic-attestation/payload/local_action_modify_payload.py
Multihost/basic-attestation/payload/test_payload_file
Multihost/basic-attestation/test.sh

Adds revocation scenario to a multi-host test and also option to use 4th system as another agent.
In future, we may want to move tenant to a separate system.

4 host scenario with revocation

---

Library/test-helpers/lib.sh

Failing tests should fail faster thanks to rlWaitForSocket timeout being reduced from 120 secs to 30 secs.

Lower rlWaitForSocket timeout to 30 seconds

---

setup/install_upstream_keylime/test.sh

Clonning keylime sources to /var/tmp/keylime_source makes eventual source code adjustment and re-installation easier.

Clone keylime sources to /var/tmp/keylime_sources

---

Library/test-helpers/lib.sh
setup/configure_tpm_emulator/test.sh

With rlRun and rlImport outside the beakerlib phase errors like
```
:: [ 16:47:49 ] :: [  BEGIN   ] :: Running 'rlImport "./test-helpers"'
/usr/share/beakerlib/logging.sh: line 133: : No such file or directory
/usr/share/beakerlib/logging.sh: line 134: : No such file or directory
```
are present in the test log.

Move rlImport under rlPhaseStart to avoid errors

---

Library/test-helpers/lib.sh
Multihost/basic-attestation/main.fmf
Multihost/basic-attestation/test.sh
TESTING.md
functional/basic-attestation-on-localhost/main.fmf
functional/basic-attestation-on-localhost/test.sh
functional/db-mariadb-sanity-on-localhost/main.fmf
functional/db-mysql-sanity-on-localhost/main.fmf
functional/db-postgresql-sanity-on-localhost/main.fmf
functional/keylime_tenant-commands-on-localhost/main.fmf
functional/keylime_tenant-commands-on-localhost/test.sh
functional/tpm_policy-sanity-on-localhost/main.fmf
functional/tpm_policy-sanity-on-localhost/test.sh
plans/distribution-keylime-tests-github-ci.fmf
plans/upstream-keylime-tests-github-ci.fmf
setup/configure_tpm_emulator/test.sh
setup/install_upstream_keylime/keylime.spec
setup/install_upstream_keylime/main.fmf
setup/install_upstream_keylime/test.sh

We have keylime listed in `recommend` instead of `require` in test `main.fmf` because on CentOS Stream it is not yet available and we do not want the provision step to fail. Eventually, keylime is later installed (or replaced) by `/setup/install_upstream_keylime` test.

Enable testing both distribution and upstream keylime

---

plans/upstream-keylime-tests-github-ci.fmf

python3-packaging package is available in powertools repo on CentOS Stream 8.

Enable powertools repo on CentOS Stream 8

---

Library/test-helpers/lib.sh
Multihost/basic-attestation/test.sh
functional/basic-attestation-on-localhost/test.sh
functional/db-mariadb-sanity-on-localhost/test.sh
functional/db-mysql-sanity-on-localhost/test.sh
functional/db-postgresql-sanity-on-localhost/test.sh
functional/keylime_tenant-commands-on-localhost/test.sh
functional/tpm_policy-sanity-on-localhost/test.sh

Rename limeWaitForTenantStatus to limeWaitForAgentStatus
Add limeWaitForAgent
Add limeWaitForAgentRegistration
Update existing tests to utilize these functions
These changes are necessary especially for CentOS Stream 8 since some operations seem to be slower there.

Implement changes in limeWaitFor functions

---

tools/conf_option_usage.sh

Simple test parser that prints out values used by tests for each keylime.conf option.
It relies on `limeUpdateConf` being used by a test.
E.g.
```
$ tools/conf_option_usage.sh 
~/devel/github/keylime-tests ~/devel/github/keylime-tests
[general]
enable_tls
True (default)
tls_check_hostnames
False (default)
True  ./Multihost/basic-attestation/test.sh
True  ./Multihost/basic-attestation/test.sh
True  ./Multihost/basic-attestation/test.sh
True  ./Multihost/basic-attestation/test.sh
ca_implementation
openssl (default)
receive_revocation_ip
127.0.0.1 (default)
${REGISTRAR_IP}  ./Multihost/basic-attestation/test.sh
${VERIFIER_IP}  ./Multihost/basic-attestation/test.sh
${VERIFIER_IP}  ./Multihost/basic-attestation/test.sh
receive_revocation_port
8992 (default)
...
```

Add conf_option_usage.sh script

---

Library/test-helpers/lib.sh
functional/basic-attestation-with-unpriviledged-agent/test.sh
setup/configure_tpm_emulator/test.sh
setup/enable_keylime_coverage/test.sh
setup/install_upstream_keylime/test.sh

Enables service file installation in the /setup/install-upstream-keylime task.
Also, since current service files start all services under `keylime` user we need to do some adjustments
in services files and `lib.sh` so that coverage measurements remain functional.

Run upstream bits as keylime user

---

functional/basic-attestation-on-localhost/main.fmf
functional/basic-attestation-on-localhost/test.sh

There are already several tests that are using certificates generated by verifier but there is no test using custom certificate except the Multihost one. As a result scenario with custom certificates is not tested in CI.
This change is updating /functional/basic-attestation-on-localhost to generate and use custom certificates.

Update basic-attestation-on-localhost to use custom certificates

---

Library/test-helpers/lib.sh
Multihost/basic-attestation/test.sh
functional/basic-attestation-on-localhost/test.sh
functional/basic-attestation-with-unpriviledged-agent/test.sh
functional/db-mariadb-sanity-on-localhost/test.sh
functional/db-mysql-sanity-on-localhost/test.sh
functional/db-postgresql-sanity-on-localhost/test.sh
functional/keylime_tenant-commands-on-localhost/test.sh
functional/tenant-allowlist-sanity/test.sh
functional/tpm_policy-sanity-on-localhost/test.sh

In CI we cannot attach logfiles and therefore cannot troubleshoot occasional failures.
This changes adds function `limeLogfileSubmit` as an alternative to `rlFileSubmit` that
prints file content to STDOUT in case the test have failed.

Add and use limeLogfileSubmit instead of rlFileSubmit

---

Library/test-helpers/lib.sh
setup/enable_keylime_coverage/main.fmf
setup/enable_keylime_coverage/test.sh

We need to set --concurrency parameter accordingly and follow
https://coverage.readthedocs.io/en/stable/cmd.html?highlight=concurrency#cmd-run

Fix code coverage measurement for async code

---

Library/test-helpers/lib.sh
setup/generate_coverage_report/test.sh

We were not specifying --source for the coverage script and therefore we were measuring only files that were executed. By specifying --source we should get more precise measurements (and lower numbers too).

Specify source parameter in coveragerc and create individual summary reports

---

functional/basic-attestation-without-mtls/main.fmf
functional/basic-attestation-without-mtls/payload/action_list
functional/basic-attestation-without-mtls/payload/autorun.sh
functional/basic-attestation-without-mtls/payload/local_action_modify_payload.py
functional/basic-attestation-without-mtls/payload/test_payload_file
functional/basic-attestation-without-mtls/test.sh

Add function/basic-attestation-without-mtls test case.
The test case runs a basic attestation using the agent with mTLS disabled.

Add test for keylime agent without mTLS

---

Multihost/basic-attestation/test.sh
functional/basic-attestation-on-localhost/test.sh
functional/basic-attestation-with-unpriviledged-agent/test.sh
functional/basic-attestation-without-mtls/test.sh
functional/db-mariadb-sanity-on-localhost/test.sh
functional/db-mysql-sanity-on-localhost/test.sh
functional/db-postgresql-sanity-on-localhost/test.sh
functional/keylime_tenant-commands-on-localhost/test.sh
functional/tenant-allowlist-sanity/test.sh
functional/tpm_policy-sanity-on-localhost/test.sh
setup/configure_tpm_emulator/test.sh
setup/install_upstream_rust_keylime/test.sh
upstream/run_keylime_tests/test.sh

Instead of defining these variable in each test /setup/configure_tpm_emulator defines them globally in /etc/profile.d/ and extends agent unit file.

[WIP] Define TPM2TOOLS_TCTI and TCTI globally in /etc/profile.d

---

functional/tenant-allowlist-sanity/test.sh

Former substitution may not have been applied and therefore
allowlist2.txt was identical to allowlist.txt.

Fix /functional/tenant-allowlist-sanity/test.sh for systems with real TPM device

---

Multihost/basic-attestation/main.fmf
Multihost/basic-attestation/test.sh
functional/basic-attestation-on-localhost/main.fmf
functional/basic-attestation-on-localhost/test.sh
functional/basic-attestation-with-unpriviledged-agent/main.fmf
functional/basic-attestation-with-unpriviledged-agent/test.sh
functional/basic-attestation-without-mtls/main.fmf
functional/basic-attestation-without-mtls/test.sh
functional/db-mariadb-sanity-on-localhost/main.fmf
functional/db-mariadb-sanity-on-localhost/test.sh
functional/db-mysql-sanity-on-localhost/main.fmf
functional/db-mysql-sanity-on-localhost/test.sh
functional/db-postgresql-sanity-on-localhost/main.fmf
functional/db-postgresql-sanity-on-localhost/test.sh
functional/keylime_tenant-commands-on-localhost/main.fmf
functional/keylime_tenant-commands-on-localhost/test.sh
functional/tenant-allowlist-sanity/main.fmf
functional/tenant-allowlist-sanity/test.sh
functional/tpm_policy-sanity-on-localhost/main.fmf
functional/tpm_policy-sanity-on-localhost/test.sh
upstream/run_keylime_tests/main.fmf

When we do not start TPM emulator in a test we do not need
tpm2-abrmd since the support for real TPM device is provided
by kernel.

Remove tpm2-abrmd usage on systems with read TPM device

---

Multihost/basic-attestation/main.fmf
Multihost/basic-attestation/test.sh
functional/basic-attestation-on-localhost/main.fmf
functional/basic-attestation-on-localhost/test.sh
functional/basic-attestation-with-unpriviledged-agent/test.sh
functional/basic-attestation-without-mtls/test.sh
plans/basic-attestation-without-revocation.fmf
setup/install_upstream_keylime/test.sh

This changes the basic attestation tests to take into account of the
KEYLIME_TEST_DISABLE_REVOCATION environment variable, which disables
ZeroMQ based revocation notification.

Add KEYLIME_TEST_DISABLE_REVOCATION envvar

---

Library/test-helpers/create_allowlist.sh
Library/test-helpers/lib.sh
functional/tpm_policy-sanity-on-localhost/test.sh
plans/distribution-keylime-tests-github-ci.fmf
setup/configure_tpm_emulator/test.sh
setup/install_upstream_keylime/test.sh

The official distributed crypto-policies should now work without the need to set the policy to the LEGACY state. It will be see in CI here.

Do not use LEGACY crypto policy

---

Multihost/basic-attestation/test.sh
functional/basic-attestation-on-localhost/test.sh
functional/basic-attestation-with-unpriviledged-agent/test.sh
functional/basic-attestation-without-mtls/test.sh
setup/install_upstream_keylime/test.sh

Also remove the leftover failure test in Multihost/basic-attestation.

Use simpler conditional to check KEYLIME_TEST_DISABLE_REVOCATION

---

plans/rust-keylime-tests.fmf

Add the test for unprivileged agent to the rust keylime agent test plan.
Signed-off-by: Anderson Toshiyuki Sasaki <ansasaki@redhat.com>

plans/rust-keylime-tests: Add basic-attestation-with-unpriviledged-agent

---

functional/basic-attestation-with-ima-signatures/test.sh
functional/install-rpm-with-ima-signature/main.fmf
functional/install-rpm-with-ima-signature/rpm-ima-sign-test.spec
functional/install-rpm-with-ima-signature/test.sh

Test requires HW TPM and therefore won't be run in CI.
Also, on F36 and lower there is an rpm issue causing test failure
https://github.com/rpm-software-management/rpm/pull/1914

Add /functional/install-rpm-with-ima-signature

---

Multihost/basic-attestation/test.sh
functional/basic-attestation-on-localhost/test.sh
functional/basic-attestation-with-unpriviledged-agent/test.sh
functional/basic-attestation-without-mtls/test.sh

The enhancement#55 introduces a means to control which revocation
mechanisms are enabled, with a single option (revocation_notifiers).
For easier transition, this resets the option as well as the old
revocation_notifier option.

Clear revocation_notifiers when revocation is disabled

---

functional/basic-attestation-on-localhost/test.sh

We need to set `revocation_notifiers` accordingly so that test scenario remains functional after `revocation_notifier_webhook` gets removed from `keylime.conf` in https://github.com/keylime/keylime/pull/795

Set revocation_notifiers in keylime.conf

---

setup/generate_coverage_report/test.sh

There is a chance that some .coverage files were not processed due to being readable only by the owner `keylime`.

Make all .coverage files root readable before processing

---

functional/ek-cert-use-ek_check_script/main.fmf
functional/ek-cert-use-ek_check_script/test.sh
functional/ek-cert-use-ek_handle-custom-ca_certs/main.fmf
functional/ek-cert-use-ek_handle-custom-ca_certs/test.sh
plans/rust-keylime-tests.fmf

Scenarios verify genuine of TPM via validating EK cert.
First of these new scenarios is related with verify
EK cert against CA certs. This test used own generated endorsement key. Second scenario verify genuine of TPM by custom script.
Fix issue #105

Test scenario checking EK on TPM

---

functional/measured-boot-policy-sanity/main.fmf

Instead of using secureboot tag let's use fmf context similarly to the current swtpm context usage.

Turn secureboot tag into a fmf context

---

functional/ek-cert-use-ek_check_script/test.sh
functional/ek-cert-use-ek_handle-custom-ca_certs/test.sh

Add to ek_check_script scenario phase, where validating
of script failed and keylime tenant cannot add agent.
Assert env variables related with endorsement key.
Fix typo in ek_handle-custom-ca_certs.

Add to ek_check_script scenario fail phase

---

setup/configure_kernel_ima_module/test.sh

Otherwise the template hash is calculated over fields in platform
native format, which confuses IMA emulator on big-endian systems.

Specify ima_canonical_fmt kernel boot parameter

---

functional/measured-boot-swtpm-sanity/main.fmf

Some of the required packages (tss) are not available on s390x.

Disable test on s390x

---

functional/tenant-allowlist-sanity/test.sh

Linked with https://github.com/keylime/keylime/pull/1061. The full allowlist API functionality added in that PR causes one of the `tenant-allowlist-sanity` tests to fail, as seen here: https://artifacts.dev.testing-farm.io/ebace054-790b-45f2-8b1a-ebce83031eec/
The issue lies in how `list2`, the allowlist that is used in the `Add keylime agent using the named allowlist` test, is created: it doesn't have an exclusion list. This PR fixes that.
Signed-off-by: Mark Bestavros <mbestavr@redhat.com>

Fix allowlist API tests failing

---

setup/generate_coverage_report/test.sh

Omit file in code coverage, which are
not really used due to obsolete python used
only on older systems.

Omit file in code coverage, upgrade test

---

functional/measured-boot-swtpm-sanity/main.fmf
plans/main.fmf
plans/rust-keylime-tests.fmf

functional/measured-boot-swtpm-sanity requires modified agent that reads measured boot log from a different location. For Python agent we can set it on the system but for the Rust agent we need to do it during compilation. By setting the proper context we can control if the test will be enabled or disabled in a test plan.
This is important for testing of distribution packages that were compiled without this hack.

Add agent and faked_measured_boot_log context

---

Multihost/basic-attestation/test.sh

Remove the unnecessary configuration files for the other components in each machine.
Also fix the revocation configuration and simplify the TLS configuration in the agent by using the `tls_dir` option
This supersedes #196

Keep only necessary configuration files in Multihost/basic-attestation

---

Library/test-helpers/lib.sh
functional/basic-attestation-on-localhost/payload-script/local_action_modify_payload.py
functional/basic-attestation-on-localhost/test.sh
functional/basic-attestation-with-custom-certificates/payload-script/local_action_modify_payload.py
functional/basic-attestation-with-custom-certificates/test.sh
functional/basic-attestation-with-unpriviledged-agent/payload-script/local_action_modify_payload.py
functional/basic-attestation-with-unpriviledged-agent/test.sh
functional/basic-attestation-without-mtls/payload-script/local_action_modify_payload.py
functional/basic-attestation-without-mtls/test.sh
functional/ek-cert-use-ek_handle-custom-ca_certs/test.sh
functional/install-rpm-with-ima-signature/test.sh
functional/measured-boot-policy-sanity/test.sh
functional/measured-boot-swtpm-sanity/test.sh
setup/install_upstream_rust_keylime/test.sh

Modify the tests to be compatible with the TOML format used in the rust agent. The main differences are:
- Booleans: on TOML format they are case sensitive. Accepted values are `true` and `false`
- Strings: on TOML format they need to be double quoted.
These changes should be compatible with INI format.
This branch is temporarily used for testing the PR:
https://github.com/keylime/rust-keylime/pull/449

Adapt the tests for the new rust agent configuration format

---

setup/install_upstream_rust_keylime/main.fmf

Adding the features "generate-bindings" to tss-esapi will enable the compilation to new architectures (PPC, S390X, etc), but will drag a new devel time dependency: bindgen.  This requires clang-devel to generate the Rust stubs to the ESAPI libraries.
Signed-off-by: Alberto Planas <aplanas@suse.com>

install_upstream_rust_keylime: require clang-devel

---

setup/configure_tpm_emulator/swtpm_permissive.te
setup/inject_SELinux_AVC_check/main.fmf
setup/inject_SELinux_AVC_check/test.sh

New setup scenario, which inject checking of AVC denials into beakerlib phases.

Inject AVC SELinux checking into beakerlib phases

---

setup/inject_SELinux_AVC_check/test.sh

by exporting `AVC_ERROR=no_avc_check` once can disable SELinux AVC check inside a test or a test phase.

Added support for AVC_ERROR variable

---

functional/keylime-non-default-ports/main.fmf
functional/keylime-non-default-ports/payload-module/action_list
functional/keylime-non-default-ports/payload-module/autorun.sh
functional/keylime-non-default-ports/payload-module/local_action_modify_payload.py
functional/keylime-non-default-ports/payload-module/test_payload_file
functional/keylime-non-default-ports/payload-script/action_list
functional/keylime-non-default-ports/payload-script/autorun.sh
functional/keylime-non-default-ports/payload-script/local_action_modify_payload.py
functional/keylime-non-default-ports/payload-script/test_payload_file
functional/keylime-non-default-ports/test.sh

Keylime mainly use default ports set in
configuration file. Set non default ports
and check if keylime work on basic
functionality properly.
#130

Use non default ports

---

Library/test-helpers/main.fmf
Multihost/basic-attestation/main.fmf
functional/basic-attestation-on-localhost/main.fmf
functional/basic-attestation-with-custom-certificates/main.fmf
functional/basic-attestation-with-ima-signatures/main.fmf
functional/basic-attestation-with-unpriviledged-agent/main.fmf
functional/basic-attestation-without-mtls/main.fmf
functional/db-mariadb-sanity-on-localhost/main.fmf
functional/db-mysql-sanity-on-localhost/main.fmf
functional/db-postgresql-sanity-on-localhost/main.fmf
functional/ek-cert-use-ek_check_script/main.fmf
functional/ek-cert-use-ek_handle-custom-ca_certs/main.fmf
functional/install-rpm-with-ima-signature/main.fmf
functional/keylime-non-default-ports/main.fmf
functional/keylime_tenant-commands-on-localhost/main.fmf
functional/keylime_tenant-ima-signature-sanity/main.fmf
functional/measured-boot-policy-sanity/main.fmf
functional/measured-boot-swtpm-sanity/main.fmf
functional/tenant-allowlist-sanity/main.fmf
functional/tpm_policy-sanity-on-localhost/main.fmf
functional/use-multiple-ima-sign-verification-keys/main.fmf
setup/install_upstream_keylime/keylime.spec
upstream/run_keylime_tests/main.fmf

`keylime-tools` is no longer being built and requiring it in tests can accidentally pull in old keylime bits.

Narrow test dependencies on keylime RPM

---

setup/configure_default_revocation_notifier/main.fmf
setup/configure_kernel_ima_module/main.fmf
setup/enable_keylime_debug_messages/main.fmf

I have observed some test aborts in CI which I believe are caused by too small test time.
This PR increases test time for some tests I have seen aborting.

Extend test time for few tests

---

upstream/run_keylime_tests/main.fmf
upstream/run_keylime_tests/test.sh

Some test scripts are not executable as standalone scripts and therefore we need to issue tests via `python -m unittest test.py`.
Also, some newly executed tests requires additional files to be present.
Finally, we are increasing test verbosity a bit.

Fix upstream test execution

---

.tmt/ref.fmf
plans/basic-attestation-without-revocation.fmf
plans/distribution-keylime-tests-github-ci.fmf
plans/rust-keylime-tests.fmf
plans/upstream-keylime-tests-github-ci.fmf

Adds initial mapping of `tmt` dynamic `ref` evaluation that has been implemented in `tmt` through https://github.com/teemtee/tmt/pull/1591

Add initial version of ref.fmf file

---

Library/test-helpers/lib.sh
setup/enable_keylime_coverage/main.fmf
setup/enable_keylime_coverage/test.sh
setup/generate_coverage_report/main.fmf
setup/generate_coverage_report/patchcov.py
setup/generate_coverage_report/test.sh

One can generate patch coverage when exporting NVR of keylime RPM to compare against, e.g.
BASELINE_KEYLIME_RPM=keylime-6.5.1-1.el9

Enable coverage measurement for installed keylime RPM

---

setup/generate_coverage_report/main.fmf
setup/generate_coverage_report/test.sh

With `BASELINE_KEYLIME_RPM=previous` one does not have to provide specific RPM NVR but the baseline would be the previous `keylime` NVR available in a repository.

Add support for BASELINE_KEYLIME_RPM=previous

---

Library/test-helpers/lib.sh
setup/enable_keylime_coverage/test.sh

We need to make coverage module available also for distribution packages.
At the same time restrict coverage `source` to keylime scripts in `/usr/bin`

Install coverage module as a system one

---

functional/db-postgresql-sanity-on-localhost/setup.psql

This could fix
https://github.com/keylime/keylime/issues/1239
Some additional details about the PostgreSQL change are at
https://www.cybertec-postgresql.com/en/error-permission-denied-schema-public/

grant all on schema public

---

plans/basic-attestation-without-revocation.fmf
plans/distribution-keylime-tests-github-ci.fmf
plans/rust-keylime-tests.fmf
plans/upstream-keylime-tests-github-ci.fmf

Seems that tag repo can be used even befor running a test plan to install some bits so removing it later can only lead to broken RPM dependencies.

Do not remove Fedora tag repository

---

upstream/run_keylime_tests/test.sh

This modifies the `upstream/run_keylime_tests` to include the `templates` directory used during the `test_restful.py` execution to generate the configuration files.

Modify tests for keylime PR 1260

---

plans/rust-keylime-tests.fmf

disable plan temporarily on Rawhide since latest Rust agent cannot be compiled

disable rust-keylime-tests plan temporarily

---

.tmt/dynamic_ref.fmf

Prepare mapping to the new `fedora-rawhide` branch for the future keylime rebase.

Update dynamic_ref with rules for Rawhide

---

functional/basic-attestation-with-custom-certificates/main.fmf
functional/basic-attestation-with-custom-certificates/test.sh

Add an intermediate CA in the chain to test multi-level CA hierarchy.
Signed-off-by: Anderson Toshiyuki Sasaki <ansasaki@redhat.com>

basic-attestation-with-custom-: Add intermediate CA

---

setup/install_upstream_rust_keylime/test.sh

Due to upcoming Python keylime agent removal we should follow the common Rust agent installation path so that executables and systemd unit files land on a system properly.

Simplify rust keylime install task

---

functional/tpm-issuer-cert-using-ecc/test.sh

This should fix occasional test failures like this:
```
:: [ 13:44:15 ] :: [  BEGIN   ] :: Running 'limeStartTPMEmulator'
Redirecting to /bin/systemctl status swtpm.service
Redirecting to /bin/systemctl status swtpm.service
Redirecting to /bin/systemctl status swtpm.service
Redirecting to /bin/systemctl start swtpm.service
:: [ 13:44:15 ] :: [   LOG    ] :: rlServiceStart: Service swtpm started successfully
:: [ 13:44:15 ] :: [   PASS   ] :: Command 'limeStartTPMEmulator' (Expected 0, got 0)
:: [ 13:44:15 ] :: [  BEGIN   ] :: Running 'limeWaitForTPMEmulator'
:: [ 13:44:15 ] :: [   INFO   ] :: rlWaitForSocket: Waiting max 20s for socket `2322' to start listening
:: [ 13:44:15 ] :: [   INFO   ] :: rlWaitForSocket: Wait successful!
:: [ 13:44:15 ] :: [   PASS   ] :: Command …
```

Move tpm2-abrmd start before tpm2_nvread call

---

setup/generate_upstream_rust_keylime_code_coverage/test.sh
setup/install_upstream_rust_keylime/main.fmf
setup/install_upstream_rust_keylime/test.sh
upstream/run_rust_keylime_tests/test.sh

This fixes broken coverage measurement due to changed filepaths and absent Rust flags. Also, always use Rustup to avoid duplicite Rust installation.

Fix broken rust coverage measurement

---

Library/test-helpers/lib.sh
functional/tenant-runtime-policy-sanity/test.sh

[Keylime PR 1314](https://github.com/keylime/keylime/pull/1314) changes how runtime policies are signed. This PR updates policy creation to generate DSSE-signed policies and test them.

Implement tests for DSSE signing

---

Library/test-helpers/lib.sh

Verifier and registrar containers deny ssh access due to insufficient permission. It can be allowed when run container with capabilities.

Run container with CAP's to allow ssh access

---

Library/test-helpers/lib.sh
container/functional/keylime_agent_container-basic-attestation/test.sh
container/functional/keylime_verifier_registrar_container-basic-attestation/test.sh

limeconPrepareImage function replace prepare image functions for specific type of container. Now is
mandatory to specify also docker file for each
call of function. limeconRun is new core function
for start of container. Is called by specific limeconRun function which add setup for specific type of container (agent, registrar, etc. )
Apply new approach to current tests and remove function for run systemd container.

Optimization container functions in helper lib

---

Library/sync/lib.sh

Define legacy (Beaker-like) environment variables `SERVERS` and `CLIENTS` if the respective role-based variables are defined by `tmt`. This change relates to the currently WIP multi-host test support for `tmt` developed in https://github.com/teemtee/tmt/pull/1790.

Define SERVERS and CLIENTS based on TMT_ROLE_ variables

---

.packit.yaml
Library/test-helpers/Dockerfile.agent
Library/test-helpers/Dockerfile.registrar
Library/test-helpers/Dockerfile.systemd
Library/test-helpers/Dockerfile.upstream.c9s
Library/test-helpers/Dockerfile.verifier
Library/test-helpers/lib.sh
Library/test-helpers/lime_con_install_upstream.sh
Library/test-helpers/lime_con_start.sh
container/functional/keylime_agent_container-basic-attestation/main.fmf
container/functional/keylime_agent_container-basic-attestation/test.sh
container/functional/keylime_verifier_registrar_container-basic-attestation/main.fmf
container/functional/keylime_verifier_registrar_container-basic-attestation/test.sh
plans/upstream-keylime-all-tests.fmf
plans/upstream-keylime-swtpm-dev.fmf
setup/install_rust_keylime_from_copr/test.sh

- Adds new Dockerfile.upstream.cs9 which prepares image with the upstream keylime
- Adopts some `limecon` optimizations from the `rhel-9-main` branch
- Modifies `limecon` functions in order to reduce the number of images built during the test
- Additional `limecon` enhancements
- Existing container tests updated and enabled in one tmt plan
Although the code of `limecon` diverge from the `rhel-9-main` branch I belive it is worth it.

Improve container support in the main branch

---

setup/install_rust_keylime_from_copr/test.sh

If the TPM_BINARY_MEASUREMENTS environment variable is set, set the
measured boot log location when installing the agent from Copr.

When installing from Copr, set the measured boot log location

---

setup/configure_kernel_ima_module/test.sh

IMA setup task could be used also on scenarios where is not used TPM, so tpm2_clear could be useless and just cause FAIL of setup task, added new conditional to check if task run on HW/QEMU TPM machine. 
Example of usage without TPM: [fapolicyd PR](https://github.com/RedHat-SP-Security/tests/pull/125/files#diff-c4ab242efdb76106e77b0c20a45b90bd44f8bd60e33b6bf3d41298c9d7037f8bR16)

Add conditional to clear tpm2 cache only on machines with HW/QEMU TPM

---

Library/sync/lib.sh
Multihost/basic-attestation/test.sh

`tmt` is changing the way how topology data are exported. This PR updates `sync` library so it works following `tmt` PR https://github.com/teemtee/tmt/pull/2072.

Export SERVERS and CLIENTS following tmt topology

---

Library/sync/lib.sh
Multihost/basic-attestation/test.sh

This is a cherry-pick of two commits from PR#391.
I have confirmed manually that these changes are correct using the followig approach:
```
$ cat > plans/multihost.fmf <<_EOF
summary: run keylime multihost test Multihost/basic-attestation
context:
swtpm: yes
agent: rust
provision:
- name: verifier
role: SERVERS
how: virtual
image: CentOS-Stream-9
connection: system
- name: registrar
role: SERVERS
how: virtual
image: CentOS-Stream-9
connection: system
- name: agent
role: CLIENTS
how: virtual
image: CentOS-Stream-9
connection: system
discover:
- name: setup
how: fmf
where:
- agent
test:
- /setup/configure_tpm_emulator
- name: test
how: fmf
where:
- verifier
- registrar
- agent
test:
- /Multihost/basic-attestation
execute:
how: tmt
adjust:
- when: distro == centos-stream-9
prepare+:
- how: …
```

cherry-pick Library/sync and Multihost updates from PR#391

---

scripts/upload_service.sh
setup/generate_coverage_report/test.sh
setup/generate_upstream_rust_keylime_code_coverage/test.sh

It seems that previously added oshi.at is not that reliable, we are observing errors like
```
curl DBI connect failed: Too many connections at /usr/share/perl5/DBIx/Connector.pm
```
Therefore adding one additional file hosting webpage and adding support for verbose mode to simplify
future troubleshooting.

Retry when uploading files

---

setup/install_rust_keylime_from_copr/test.sh

We should make the setup task to fail when COPR repo cannot be used.

Use skip_if_unavailable=False for COPR repo

---

Library/sync/lib.sh

This is a backport of the patch from https://github.com/RedHat-SP-Security/keylime-tests/pull/395

Change TMT_TOPOLOGY_SH to TMT_TOPOLOGY_BASH

---

.packit.yaml

Since Packit RFE https://github.com/packit/packit-service/issues/2051 implemented we can unify .packit.yaml in the main branch so we won't have to customize it when rebasing tests to rhel-9-main or fedora-rawhide branch.

Unify .packit.yaml in the main branch

---

Library/sync/lib.sh

backport of the PR https://github.com/RedHat-SP-Security/keylime-tests/pull/399

declare associative arrays when TMT_TOPOLOGY_BASH is not defined

---

Library/test-helpers/main.fmf

This is a very minimal PR, to enable further changes. The main goal here is to have `keylime_tenant` to always output JSON, and use the `jq` tool to properly parse and read status/info from the schema, rather than grep specific strings in log messages.

Add `jq` utility to test-helpers

---

functional/basic-attestation-with-custom-certificates/test.sh

Previously, the rust keylime agent supported only a single file in the `trusted_client_ca` option.  The support for a list in `trusted_client_ca` was added in https://github.com/keylime/rust-keylime/pull/604.

Remove workaround for multiple CA certificates

---

functional/keylime_tenant-commands-on-localhost/test.sh
functional/measured-boot-swtpm-sanity/test.sh

Related to https://github.com/keylime/keylime/pull/1414

Allow (temporarily) exit codes 0 and 1 for `regstatus`, `cvstatus` and `add` (with incorrect PCR banks)

---

.github/workflows/shellcheck.yml

Differential ShellCheck is a GitHub Action that performs differential ShellCheck scans on shell scripts changed via PR and reports results directly in PR.
Your scripts are in great shape, but I think you might find the `differential-shellcheck` Action useful. It is able to produce reports in SARIF format. GitHub understands this format and is able to display it nicely as a PR comment, and on the `Files Changed` tab, please see below.
Documentation is available at [@redhat-plumbers-in-action/differential-shellcheck](https://github.com/redhat-plumbers-in-action/differential-shellcheck#readme). Let me know If you are missing some feature or setting. I'm always happy to extend functionality.

ci(lint): add shell linter - Differential ShellCheck

---

.packit.yaml

dnf5 used in Rawhide doesnt work well with the Testing Farm infrastructure and therefore we need to disable testing on Rawhide temporarily.

Disable Packit CI on Rawhide due to infra issues

---

Library/test-helpers/lib.sh

The current timeout implementation does not account for the time spent in keylime_tenant.

Improve timeouts to account for time spent in keylime_tenant

---

.packit.yaml

Commonly used CentOS Stream 9 mirrors are one week behind the main repository. Therefore let's use the main repo instead of mirrors.

Use development C9S repos in .packit.yaml

---

.packit.yaml
plans/distribution-c9s-keylime-tests-github-ci.fmf

Backport `.packit.yaml` update and distribution testplan updates from `rhel-9-main` so that they won't be lost with a future rewrite.

Backport fixes from rhel-9-main

---

Multihost/basic-attestation/test.sh

backporting the fix that is already used in main and rhel-9-main

Fix check for TMT_TOPOLOGY_BASH

---

plans/distribution-c9s-keylime-tests-github-ci.fmf
plans/upstream-basic-attestation-without-revocation.fmf
plans/upstream-keylime-all-tests.fmf

Sometimes it happens that a test system already contains a newer version of epel-release. Weird but true.

Make epel-release install always pass

---

functional/basic-attestation-with-custom-certificates/main.fmf
functional/basic-attestation-with-custom-certificates/test.sh
functional/keylime-non-default-ports/main.fmf
functional/keylime-non-default-ports/test.sh

Apply condtionally for specific version of rhel and fedoras.

Set keylime_port_t label for random ports use in tests

---

functional/agent_UUID_assignment_options/test.sh
functional/basic-attestation-on-localhost/test.sh
functional/ek-cert-use-ek_check_script/test.sh
update/basic-attestation-on-localhost/test.sh

Debug logging slows test execution significantly and is a root cause of various test failures. We should not be using it unless we are troubleshooting an actual problem.

Remove logging on debug level

---

compatibility/basic-attestation-on-localhost-api-version-bump/test.sh
compatibility/basic-attestation-on-localhost-with-allowlist-excludelist/test.sh
functional/agent_UUID_assignment_options/test.sh
functional/basic-attestation-on-localhost/test.sh
functional/durable-attestion-sanity-on-localhost/test.sh
functional/ek-cert-use-ek_check_script/test.sh
regression/issue-1380-agent-removed-and-re-added/test.sh
sanity/keylime-secure_mount/test.sh
update/basic-attestation-on-localhost/test.sh

Debug logging slows test execution significantly and is a root cause of various test failures. We should not be using it unless we are troubleshooting an actual problem.

Remove keylime logging on DEBUG level

---

plans/distribution-c9s-keylime-swtpm-dev.fmf

Adding new plan distribution-c9s-keylime-swtpm-dev.fmf which is disabled on main and it is there only for future rewrites of rhel-9-main

Added plan distribution-c9s-keylime-swtpm-dev.fmf

---

upstream/run_rust_keylime_tests/test.sh

This is a workaround for https://github.com/xd009642/tarpaulin/issues/1388
The issue was fixed upstream but not released yet, which makes our pipelines to fail.
This also adds the --engine llvm to try to solve the eventual timeout that happens on our tests.

upstream: Fix tarpaulin issues with dropped -v option

---

Library/test-helpers/lib.sh

Given that `keylime_create_policy` script has more features and we expect users to use it it is better to do the conversion to JSON policy using `keylime_create_policy` instead of `keylime_convert_runtime_policy`.

Use keylime_create_policy instead of keylime_convert_runtime_policy

---

functional/keylime-non-default-ports/test.sh

Setting non default ports for keylime requires
additional SELinux labeling for used ports.
When test is rerun in same enviroment ports are
not needed set again and setup could cause failures in test.

Set label for ports only if are not yet set

---

Multihost/basic-attestation/test.sh
container/functional/keylime_agent_container-basic-attestation/test.sh
container/functional/keylime_all_in_container-basic-attestation/test.sh
container/functional/keylime_ipv6_multihost/test.sh
container/functional/keylime_verifier_registrar_container-basic-attestation/test.sh

The verifier does not contact the registrar in any way since this commit: https://github.com/keylime/keylime/commit/bd5de712acdd77860e7dc58969181e16c7a8dc5d

registrar_ip is not needed for the verifier

---

setup/install_rust_keylime_from_copr/test.sh
setup/install_upstream_keylime/test.sh

While removing keylime yum has decided to remove some packages that were required by tests.

Use --noautoremove when removing installed keylime

---

functional/iak-idevid-register-with-certificates/intermediate.cnf
functional/iak-idevid-register-with-certificates/main.fmf
functional/iak-idevid-register-with-certificates/root.cnf
functional/iak-idevid-register-with-certificates/test.sh

This is an end to end test for the IDevID and IAK patches:
[1](https://github.com/keylime/keylime/pull/1416),  [2](https://github.com/keylime/rust-keylime/pull/608), [3](https://github.com/keylime/keylime/pull/1477), [4](https://github.com/keylime/rust-keylime/pull/669)
The test recreates the IAK and IDevID keys out of band of the agent (using tpm2_tools), and sets up a CA to create certs for the keys. The agent attempts to register with the keys (checking the keys match the internal keys in the process) and fails when the CA has not been added as trusted, then succeeds when the CA is added.
There may be missing parts or oversights (for example I was not sure how to generate the nitrate part of the fmf file)
The test currently should only be run for fedora-39

Add tests for the IAK and IDevID patches

---

Library/test-helpers/lib.sh
container/functional/keylime_all_in_container-basic-attestation/test.sh
setup/configure_kernel_ima_module/main.fmf
setup/install_etc_keylime_conf/main.fmf
setup/install_etc_keylime_conf/test.sh

The goal of these changes is making possible to run test
`/container/functional/keylime_all_in_container-basic-attestation`
on a RHEL-8 system (with no keylime installed) while all keylime components are running from a container.

Modify tests to enable limited container test execution on RHEL-8

---

Library/test-helpers/lib.sh
container/functional/keylime_all_in_container-basic-attestation/test.sh
setup/configure_kernel_ima_module/main.fmf
setup/install_etc_keylime_conf/main.fmf
setup/install_etc_keylime_conf/test.sh

Backport of https://github.com/RedHat-SP-Security/keylime-tests/pull/528 to the main branch.

Modify tests to enable running container test on RHEL-8

---

compatibility/basic-attestation-on-localhost-api-version-bump/test.sh

On `compatibility/basic-attestation-on-localhost-api-version-bump`:
- Avoid compilation error when using nightly by updating ahash crate to version 0.8.7

Workaround ahash compilation issue with nightly rustc

---

Library/sync/install-provider
Library/sync/lib.sh
Library/sync/sync-get.service

Limit the size of a status reported over a network to last 100 statuses.

sync: report only last 100 statuses over ncat

---

upstream/run_rust_keylime_tests/test.sh

Avoid a deadlock by using a single thread during code test coverage measurement.
EDIT: AFAIK, this deadlock can happen only when running multiple threads under `tarpaulin` and an external process is started with `Command::run()`.

upstream/run_rust_keylime_tests: Use a single thread

---

setup/install_upstream_rust_keylime/test.sh

Replace the nightly version usage with a pinned version (1.74.1) that supports code instrumentation for test coverage measurement by `tarpaulin`

install_upstream_rust_keylime: Pin rust compiler version 1.74.1

---

functional/install-rpm-with-ima-signature/main.fmf
functional/install-rpm-with-ima-signature/test.sh
plans/main.fmf

- workaround bz#2269992 by switching sdubby package with grubby
- fix test failure on Rawhide in  /functional/install-rpm-with-ima-signature by avoiding expect usage in rpm --addsign

Replace sdubby with grubby, bz#2269992

---

Library/test-helpers/lib.sh
functional/tenant-runtime-policy-sanity/test.sh

Keylime does not allow the trivial passing of signature verification on the self-signed certificate embedded in the DSSE envelope of a signed policy anymore. Instead, it requires that a public key for signature verification be given by the user. Therefore, pass the public key needed for signature verification via the command line.
This PR requires agreement on https://github.com/keylime/keylime/pull/1482

Provide public key for signature verification on command line

---

functional/iak-idevid-register-with-certificates/main.fmf
functional/iak-idevid-register-with-certificates/test.sh

Rawhide already containt pre-built openssl-provider so we should be using it.

Stop building tpm2-openssl provider

---

setup/generate_coverage_report/patchcov.py

Should fix the following traceback:
Traceback (most recent call last):
File "/var/ARTIFACTS/work-e2e-with-revocationmuq079lo/packit-ci/e2e-with-revocation/discover/default-0/tests/setup/generate_coverage_report/./patchcov.py", line 197, in <module>
v = get_patch_coverage(patch_path, db_path)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/var/ARTIFACTS/work-e2e-with-revocationmuq079lo/packit-ci/e2e-with-revocation/discover/default-0/tests/setup/generate_coverage_report/./patchcov.py", line 133, in get_patch_coverage
line_no = int(re.sub(r'.*\+([0-9]+),.*', r'\1', line)) - 1
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '@@ -0,0 +1 @@'

Update regexp as comma is not always present

---

plans/distribution-c9s-keylime-multihost.fmf

It is handy not to disable the plan on distro!=c9s so that we can schedule it eventually on a different distro.

Do not disable distribution-c9s-keylime-multihost

---

compatibility/basic-attestation-on-localhost-api-version-bump/test.sh

Instead of using an old version of the agent, use the current code, but replacing the API version with an older supported version.
This will reduce the chaces of compilation issues due to updated rust compiler or changes in the availability of dependencies.

Use current code with old version on API bump test

---

compatibility/basic-attestation-on-localhost-api-version-bump/test.sh

This change is to cover a corner case when the python components API version is bumped before the agent API version is bumped.
In such a case, the latest old supported API version for the verifier would be the current agent API version. Then it is necessary to use the second to last to cause a difference in the API version.

Use the latest old supported version that is not the current version to test API bump

---

functional/iak-idevid-register-with-certificates/test.sh

With the new [patch to enable handles](https://github.com/keylime/rust-keylime/pull/785) the phrasing here has changed to be less ambiguous.

change IDevID grep phrase check

---

setup/install_upstream_rust_keylime/main.fmf
setup/install_upstream_rust_keylime/test.sh

The current stable rust compiler (1.78.0) has the features necessary to instrument the code for coverage measurement by cargo-tarpaulin.
This change removes the pinning of the version, using the current stable rust compiler instead.
This also installs the coverage generation tools only when code coverage is requested.
Fix #584

install_upstream_rust_keylime: Do not pin the rustc version

---

setup/install_upstream_keylime/keylime.spec

A change in DNF5 could be a root cause for current test failures on Rawhide.
DNF5 is pulling the real `keylime-base` as a require of `keylime-agent-rust`, because our `keylime-99` does not provide `user(keylime)` and `group(keylime)`.
The following can be seen in the test log:
```
keylime-99-1.noarch
keylime-base-7.10.0-1.fc41.x86_64
```
With this update we are adding Obsoletes definitions to keylime SPEC so that subpackages won't be pulled in.

Add Obsoletes to keylime-99 SPEC

---

functional/keylime_tenant-commands-on-localhost/test.sh
functional/keylime_tenant-ima-signature-sanity/test.sh

Because of
https://github.com/keylime/keylime/pull/1531
the usage of -f parameter is optional now.
By removing it from a few tests we exercise both variants.

Remove keylime_tenant -f parameter from a few tests

---

functional/iak-idevid-register-with-certificates/test.sh

At the moment, the IDevID test (```iak-idevid-register-with-certificates```) works because the test ```ek-cert-use-ek_handle-custom-ca_certs``` previously ran and created the tpm certs folder.
This change makes sure the folder has been created, allowing the test to be run independently of other tests running.

Stop IDevID test being dependant on a previous test running

---

Library/test-helpers/Dockerfile.agent
Library/test-helpers/Dockerfile.registrar
Library/test-helpers/Dockerfile.tenant
Library/test-helpers/Dockerfile.upstream.c10s
Library/test-helpers/Dockerfile.verifier
Library/test-helpers/lib.sh
Library/test-helpers/lime_con_install_upstream.sh
container/functional/keylime_agent_container-basic-attestation/test.sh
container/functional/keylime_all_in_container-basic-attestation/test.sh
container/functional/keylime_ipv6_multihost/test.sh
container/functional/keylime_verifier_registrar_container-basic-attestation/test.sh
plans/distribution-c9s-keylime-swtpm-dev.fmf
plans/distribution-c9s-keylime-tests-github-ci.fmf
plans/upstream-keylime-containers.fmf
plans/upstream-keylime-swtpm-dev.fmf
setup/apply_workarounds/keylime_tests_workarounds.te.el10

Since we are no longer able to install upstream keylime to c9s we should also base our container tests and dockerfiles on c10s.

Move to c10s based dockerfiles

---

functional/iak-idevid-persisted-and-protected/intermediate.cnf
functional/iak-idevid-persisted-and-protected/main.fmf
functional/iak-idevid-persisted-and-protected/root.cnf
functional/iak-idevid-persisted-and-protected/test.sh

Fixes #587 
This is a test for IDevIDs and IAKs that are persisted in the TPM and are accessed via handle rather than regenerated. These keys may also be protected by password, this is also tested, as is the change to enable hex passwords for the TPM.
Relevant PRs:
[agent: enable persisted and protected IDevIDs](https://github.com/keylime/rust-keylime/pull/785), [agent: enable hex passwords for the TPM](https://github.com/keylime/rust-keylime/pull/769), [server: add config options](https://github.com/keylime/keylime/commit/7b3ea56aae40dc04ae4f28f0147486f90ff547fa)

Persisted and protected IDevID and IAK test

---

Library/test-helpers/Dockerfile.webhook
Library/test-helpers/lib.sh
container/functional/keylime_ipv6_multihost/test.sh
functional/basic-attestation-on-localhost/test.sh
functional/basic-attestation-with-custom-certificates/test.sh
functional/keylime-non-default-ports/test.sh

Setup TLS for  the server started to receive the revocation notification.
This is necessary for https://github.com/keylime/keylime/pull/1566, which requires TLS to be used for communication to the revocation notification webhook in case TLS is enabled in the configuration file.

Use TLS for revocation notification webhook

---

Library/test-helpers/Dockerfile.webhook
Library/test-helpers/lib.sh
container/functional/keylime_ipv6_multihost/test.sh
functional/basic-attestation-on-localhost/test.sh
functional/basic-attestation-with-custom-certificates/test.sh
functional/keylime-non-default-ports/test.sh

Backport the changes from `main` to use TLS on revocation notification webhook.
This is necessary to make tests on https://gitlab.com/redhat/centos-stream/rpms/keylime/-/merge_requests/37 to pass.

Backport changes to use TLS on revocation notification webhook

---

setup/configure_kernel_ima_module/main.fmf

The test requires `ima-evm-utils`, but it was missing in the main.fmf

setup/configure_kernel_ima_module: Add missing dependency

---

functional/keylime_policy-commands/test.sh

Previously, the keylime_policy command would set the IMA template hash algorithm to follow the algorithm set through --algo option.
This was an incorrect behavior and was recently fixed. Now the IMA template hash algorithm is hardcoded as SHA-1, following kernel implementation.

keylime_policy-commands: Do not expect algorithm in policy

---

.github/workflows/test_parity.yml
scripts/check_upstream_test_parity.sh

Adds a new check which fails when there are missing tests in keylime upstream CI plans.

Add CI parity test

---

functional/keylime_policy-commands/test.sh

Replace the curl command with the limeCopyKeylimeFile which will try to find the requested file locally before resorting to downloading the file.

keylime_policy-commands: Use limeCopyKeylimeFile instead of curl

---

functional/webhook-certificate-on-localhost/test.sh

Fixes the failure in `functional/webhook-certificate-on-localhost` due to changes in `ca-certificates`.

Use unique subject for CA certificates

---

compatibility/basic-attestation-on-localhost-api-version-bump/test.sh
functional/basic-attestation-with-custom-certificates/test.sh
functional/install-rpm-with-ima-signature/test.sh

Adding the CA certificate to 'trusted_server_ca' configuration should be sufficient.

Do not add webhook server certificate to system CA trust store

---

functional/keylime-policy-commands/main.fmf
scripts/check_upstream_test_parity.sh

Adds possibility to ignore tests tagged with `not-agent-upstream-CI` and `not-keylime-upstream-CI` in the upstream CI test parity check.

Add upstream CI test filtering capabilities

---

upstream/run_keylime_tests/test.sh

This will make it use primarily the code from the source tree we are testing, instead of what is installed (rpm) in the system.

upstream/run_keylime_tests: define PYTHONPATH pointing to keylime source

---

Library/test-helpers/lib.sh
setup/install_rust_keylime_from_copr/test.sh
setup/install_upstream_rust_keylime/test.sh

Some of the log messages were moved from the `keylime_agent` to the `keylime` library.  With these changes, the messages logged by the keylime library are also visible.

Set log level for the rust keylime lib as well

---

.github/dependabot.yml

The bot can automatically update github actions when new versions are released.

Enable dependabot for automatic github actions updates

---

compatibility/basic-attestation-on-localhost-api-version-bump/test.sh
plans/main.fmf

Replace the re-compilation of the agent using an older version with a simple
reconfiguration of  the agent enabling the desired API version.

Update basic-attestation-on-localhost-api-version-bump for the agent with multiple API

---

setup/generate_upstream_rust_keylime_code_coverage/test.sh

This adds a line to upload the upstream coverage report file as an artifact.
Also, compress the files before uploading.

Upload rust upstream coverage to be stored as an artifact

---

Library/test-helpers/lib.sh
setup/install_rust_keylime_from_copr/test.sh
setup/install_upstream_rust_keylime/test.sh

Some of the log messages were moved from the keylime_agent to the keylime library.  With these changes, the messages logged by the keylime library are also visible.
This is a cherry pick of da8d7827ca65e6ea0630b3d77d809da5073b294f

Set  the log level for the keylime lib as well

---

regression/CVE-2023-3674/test.sh

This is a cherry-pick of 0e7afa6ab7cf1f4969f87ad50a5e76dcb75c6243
This adds an alternative acceptable error message for the raised exception.

Add another acceptable error message for CVE-2023-3674 test

---

Library/test-helpers/lib.sh
functional/iak-idevid-register-with-certificates/main.fmf
functional/iak-idevid-register-with-certificates/test.sh
regression/CVE-2023-3674/test.sh
setup/install_rust_keylime_from_copr/test.sh
setup/install_upstream_rust_keylime/test.sh

This brings the `fedora-40` branch in sync with the `fedora-rawhide` branch.
This cherry picks:
- 0e7afa6ab7cf1f4969f87ad50a5e76dcb75c6243
- da8d7827ca65e6ea0630b3d77d809da5073b294f
- 55a403f0279a22140163e7eebdd311d22a5b4b24
- cfe787dd715e9b167d9d7a8ee165ae0cb59fb89b
- 34ecca32e3b3ba94a0a4c3994ca86f387064714d

fedora-40: Cherry pick fixes for IDevID/IAK test

---

Library/test-helpers/lib.sh
functional/iak-idevid-register-with-certificates/main.fmf
functional/iak-idevid-register-with-certificates/test.sh
regression/CVE-2023-3674/test.sh
setup/install_rust_keylime_from_copr/test.sh
setup/install_upstream_rust_keylime/test.sh

This brings the `fedora-41` branch in sync with the `fedora-rawhide` branch.
This cherry picks:
- 0e7afa6ab7cf1f4969f87ad50a5e76dcb75c6243
- da8d7827ca65e6ea0630b3d77d809da5073b294f
- 55a403f0279a22140163e7eebdd311d22a5b4b24
- cfe787dd715e9b167d9d7a8ee165ae0cb59fb89b
- 34ecca32e3b3ba94a0a4c3994ca86f387064714d

fedora-41: Cherry pick fixes for IDevID/IAK test

---

Library/test-helpers/lib.sh
functional/keylime_create_policy-static-data/main.fmf

backport changes from 
https://github.com/RedHat-SP-Security/keylime-tests/pull/721

Complete test migration to keylime-policy tool

---

.github/dependabot.yml
.github/workflows/shellcheck.yml

This enables dependabot on fedora-rawhide and cherry-picks the workflow fixes from `main`

Enable dependabot on fedora-rawhide and cherry-pick workflow updates

---

compatibility/basic-attestation-on-localhost-api-version-bump/test.sh
plans/distribution-fedora-keylime.fmf
setup/generate_coverage_report/patchcov.py

This updates the test on `fedora-rawhide` to work with the agent with multiple API versions

Cherry-pick changes for basic-attestation-on-localhost-api-version-bump from main

---

Library/test-helpers/lib.sh
regression/keylime-agent-option-override-through-envvar/test.sh
sanity/keylime-secure_mount/test.sh

The PR https://github.com/keylime/rust-keylime/pull/1018 moves code from the `keylime-agent` application to the `keylime` library.
This makes it necessary to set the log level for both the application and the library so that the messages are logged as expected.
This also changes the `sanity/keylime-secure_mount` test to ignore the source of the expected log.

Enable logs generated by the keylime library

---

Library/test-helpers/lib.sh
functional/basic-attestation-with-custom-certificates/main.fmf
functional/basic-attestation-with-custom-certificates/test.sh
functional/webhook-certificate-on-localhost/main.fmf
functional/webhook-certificate-on-localhost/test.sh

Two current scenarios use as default sign algorithm RSA, adjust these to make it configurable to use RSA or ML-DSA-65. Part of this change is implementing function for key generation, current certgen library cannot generate PQ algorithm.

Adjust test scenario to use sign PQC algoritms

---

functional/webhook-certificate-on-localhost/test.sh

Shortening the check for an error message to make it compatible both with the old code and the new code introduced in https://github.com/keylime/keylime/pull/1784.

Update expected error due to keylime PR#1784

---

Library/test-helpers/lib.sh

Processes like keylime_ima_emulator do not have / before its name in process listing.

Fix pattern for keylime process detection

---

Library/test-helpers/Dockerfile.agent
Library/test-helpers/Dockerfile.registrar
Library/test-helpers/Dockerfile.tenant
Library/test-helpers/Dockerfile.upstream.c10s
Library/test-helpers/Dockerfile.verifier
Library/test-helpers/Dockerfile.webhook
Library/test-helpers/lib.sh
container/compatibility/registrar_version_compatibility/Dockerfile.keylime.c10s
container/compatibility/registrar_version_compatibility/Dockerfile.upstream.c10s
container/functional/keylime_agent_container-basic-attestation/test.sh
plans/upstream-keylime-containers.fmf
setup/configure_swtpm_device/test.sh

Configure `TCTI` and `TPM2TOOLS_TCTI` variables in `/setup/configure_swtpm_device` task both for the pull and push based agents but only if some other `/dev/tpm` device hasn't been configured already.
Similar setup is already being made in `/setup/configure_tpm_emulator` task.

Set TCTI variables during swtpm device setup

---

regression/db-connection-leak-reproducer/main.fmf

Do not register /regression/db-connection-leak-reproducer as a Rust agent CI test.

Do not register as rust-agent CI test

---

Library/test-helpers/lib.sh
Library/test-helpers/main.fmf
functional/add-agent-with-malformed-ek-cert/main.fmf
functional/add-agent-with-malformed-ek-cert/test.sh
setup/configure_swtpm_device/test.sh
setup/configure_tpm_emulator/test.sh

We add units for configuring swtpm to provide a malformed EK certificate as per python-cryptography (due to its stricter ASN.1 parsing), but that OpenSSL considers valid -- we have encountered a few such certificates in the field already.
We add also a test to check whether we are able to add an agent that has an EK that exhibits this malformation characteristics.

Add a way to configure swtpm with malformed EK and a test using it

---

setup/configure_swtpm_device/test.sh
setup/configure_tpm_emulator/test.sh

Because of
```
ERROR: Must specify the EK public key path
Usage: tpm2_getekcertificate [<options>] <arguments>
Where <options> are:
[ -o | --ek-certificate=<value>] [ -X | --allow-unverified] [ -u | --ek-public=<value>] [ -x | --offline]
[ --raw]
```

Disable EK check on s390x
