- Library/test-helpers/lib.sh
- Multihost/basic-attestation/test.sh
- functional/basic-attestation-on-localhost/test.sh
- setup/enable_keylime_coverage/main.fmf
- setup/enable_keylime_coverage/test.sh
- setup/generate_coverage_report/main.fmf
- setup/generate_coverage_report/test.sh
Starts keylime services via "coverage run" when COVERAGE environment variable is defined and non-empty.
This enable gathering code coverage metrics.
> [WIP] Enable code coverage measuring for keylime services

- Library/sync/install-provider
- Library/sync/runtest.sh
- Library/sync/sync-block
- Library/sync/sync-save
- Library/sync/sync-save.service
- Library/sync/sync-set
Adds support for SYNC_PROVIDER where synchronization statuses are tracked by an independent server.
Not really useful for keylime but it makes the implementation somehow complete.
> SYNC_PROVIDER support

- Library/test-helpers/lib.sh
- functional/db-mariadb-sanity-on-localhost/main.fmf
- functional/db-mariadb-sanity-on-localhost/setup.sql
- functional/db-mariadb-sanity-on-localhost/test.sh
- functional/db-mysql-sanity-on-localhost/main.fmf
- functional/db-mysql-sanity-on-localhost/setup.sql
- functional/db-mysql-sanity-on-localhost/test.sh
- functional/db-postgresql-sanity-on-localhost/main.fmf
- functional/db-postgresql-sanity-on-localhost/setup.psql
- functional/db-postgresql-sanity-on-localhost/test.sh
Currently failing due to a bug in keylime
https://github.com/keylime/keylime/issues/863
> Add db sanity tests

- setup/install_upstream_keylime/test.sh
These steps are necessary when downgrading keylime version.
> Clear DB migration files

- .packit.yaml
- Library/test-helpers/lib.sh
- setup/configure_tpm_emulator/test.sh
- setup/install_upstream_keylime/test.sh
Also enable packit testing in CentOS Stream 8
> Change COPR repo and enable packit testing in CentOS Stream 8

- setup/generate_coverage_report/test.sh
Packit has introduce new environment variables that enable us more precise patch generation.
Moreover, former usage of PACKIT_TARGET_SHA was wrong as it points to the target HEAD
and not the common ancestor.
> Utilize new PACKIT env variables to improve git handling

- setup/generate_coverage_report/patchcov.py
Implements two changes:
- support for test codes of length >1 character
- present (not count) code coverage for unchanged lines
> Improved presentation of code coverage

- functional/tenant-allowlist-sanity/test.sh
- functional/tpm_policy-sanity-on-localhost/test.sh
This is necessary due to https://github.com/keylime/keylime/pull/974
> remove vtpm_policy

- Library/sync/main.fmf
- Library/test-helpers/main.fmf
Adding to fmf file reference to number of
test case in TCMS/nitrate.
> Add ref to test case in nitrate.

- setup/install_upstream_keylime/test.sh
> setup/install_upstream_keylime: conditionalize python3-zmq install

- Library/test-helpers/lib.sh
- setup/install_upstream_rust_keylime/test.sh
This is required due to https://github.com/keylime/rust-keylime/pull/428
> Update limeUpdateConf to edit both keylime.conf and keylime-agent.conf

- functional/keylime_tenant-ima-signature-sanity/main.fmf
- functional/keylime_tenant-ima-signature-sanity/test.sh
Tenant verification options check validity of IMA
file signature verification key which is sign by
gpg key.Check in scenario if this options works
properly.
Fix issue #131
> Scenario testing tenant signature verification options

- functional/tenant-allowlist-sanity/test.sh
Removed pgp keys created by test.
Backup keys from previous setup.
> Update test to remove pgp keys

- setup/install_upstream_keylime/test.sh
These new deps are necessary for the fix/workaround for issue https://github.com/keylime/keylime/issues/944
> Add python3-pyasn1 and python3-pyasn1-modules to the list of deps

- Library/test-helpers/lib.sh
- functional/multiple-files-with-ima-signature/main.fmf
- functional/multiple-files-with-ima-signature/test.sh
> Update scenario to use multiple ima signature verification keys

- setup/configure_tpm_emulator/swtpm_permissive.te
- setup/inject_SELinux_AVC_check/main.fmf
- setup/inject_SELinux_AVC_check/test.sh
Doing due to adding setup task to packit.fmf [PR](https://github.com/RedHat-SP-Security/keylime-selinux/pull/5/commits/84bb71391e7fec9ccd804447b3d4c2d650a006e0).
> Inject AVC SELinux checking into beakerlib phases 

- plans/basic-attestation-without-revocation.fmf
- plans/distribution-keylime-tests-github-ci.fmf
- plans/rust-keylime-tests.fmf
- plans/upstream-keylime-tests-github-ci.fmf
- setup/enable_keylime_debug_messages/main.fmf
- setup/enable_keylime_debug_messages/test.sh
Introduce new setup task that can be added to a test plan.
> Enable keylime logging on DEBUG level

- functional/basic-attestation-on-localhost/test.sh
We should test that running scripts on allowlist won't affect attestation.
> Add two allowed scripts to the test scenario

- plans/basic-attestation-without-revocation.fmf
- plans/distribution-keylime-tests-github-ci.fmf
- plans/rust-keylime-tests.fmf
- plans/upstream-keylime-tests-github-ci.fmf
This service seems to be enabled and running by default which increases RAM consumption.
> Disable dnf-makecache.service

- functional/agent_UUID_assignment_options/test.sh
Remove for all distros except f36 and f37
bz#2165055
> Disable agent uuid assignment test due to bz#2165055

- Library/test-helpers/lib.sh
- plans/rust-keylime-tests.fmf
- setup/generate_usptream_rust_keylime_code_coverage/main.fmf
- setup/generate_usptream_rust_keylime_code_coverage/test.sh
- setup/install_upstream_rust_keylime/test.sh
- upstream/run_rust_keylime_tests/main.fmf
- upstream/run_rust_keylime_tests/test.sh
Pull request is still in progress and blocked due [Graceful shutdown of the agent](https://github.com/keylime/rust-keylime/issues/363) issue in keylime rust agent upstream.
> Measured code coverage for rust

- setup/install_upstream_keylime/test.sh
Needed due to changes in https://github.com/keylime/keylime/pull/1331
> Added installation of python3-jsonschema package

- setup/generate_coverage_report/patchcov.py
Should improve detection of a code change inside a patch and avoid counting `}` as not executed lines.
> Improve patch coverage precision

- setup/generate_coverage_report/patchcov.py
Backporting to the rhel-9-main branch
> Extend set of ignored lines in patchcov.py

- Library/sync/lib.sh
backport of https://github.com/RedHat-SP-Security/keylime-tests/pull/371
> Define SERVERS and CLIENTS based on TMT_ROLE_ variables - backport rhel-9-main

- Library/sync/lib.sh
backport of https://github.com/RedHat-SP-Security/keylime-tests/pull/371
> Define SERVERS and CLIENTS based on TMT_ROLE_ variables - backport rhel-9.1.0

- .packit.yaml
- plans/distribution-c9s-keylime-tests-github-ci.fmf
- plans/main.fmf
- plans/upstream-basic-attestation-without-revocation.fmf
- plans/upstream-keylime-all-tests.fmf
- plans/upstream-keylime-swtpm-dev.fmf
Fedora bug 2171376 should be fixed by now.
> Enable Packit CI on all Fedoras

- Library/test-helpers/lib.sh
Function provide start of systemd container.
> Add previously removed limeconRunSystemd func

- scripts/upload_service.sh
oshi.at does create short URLs which do not contain filename. This is a problem for downloading as we need to know the name of the downloaded file. Fortunately it is possible to add filename at the end of the download link manually.
> Preserve filename during upload

- plans/upstream-keylime-all-tests.fmf
- sanity/keylime-secure_mount/main.fmf
- sanity/keylime-secure_mount/test.sh
Secure mount sanity check agent secure mount
of dir.
> Secure mount sanity scenario

- Multihost/basic-attestation/test.sh
This is necessary for interoperability testing with older keylime
> Add allowlist support to multihost test

- Multihost/basic-attestation/main.fmf
- Multihost/basic-attestation/payload-script/local_action_modify_payload.py
- setup/switch_git_branch/test.sh
Compatibility changes necessary for interoperability testing
> Update multihost test due to interoperability testing

- functional/basic-attestation-with-custom-certificates/main.fmf
- functional/basic-attestation-with-custom-certificates/test.sh
- functional/keylime-non-default-ports/main.fmf
- functional/keylime-non-default-ports/test.sh
- plans/distribution-fedora-keylime.fmf
Apply condtionally for specific version of rhel and fedoras.
> Set keylime_port_t label for random ports use in tests

- plans/distribution-fedora-keylime.fmf
Add fedora distribution plan for CI
and update description of rhel distribution
plan.
> Add fedora distribution plan for CI

- plans/distribution-c9s-keylime-tests-github-ci.fmf
- plans/upstream-basic-attestation-without-revocation.fmf
- plans/upstream-keylime-all-tests.fmf
Backporting a fix for the main branch
> Make epel-release install always pass

- Library/test-helpers/Dockerfile.agent
- Library/test-helpers/Dockerfile.registrar
- Library/test-helpers/Dockerfile.upstream.c9s
- Library/test-helpers/Dockerfile.verifier
- Library/test-helpers/lib.sh
- Library/test-helpers/lime_con_install_upstream.sh
- Library/test-helpers/lime_con_start.sh
- container/functional/keylime_agent_container-basic-attestation/test.sh
- container/functional/keylime_verifier_registrar_container-basic-attestation/main.fmf
- container/functional/keylime_verifier_registrar_container-basic-attestation/test.sh
Bring changes to allow setting images for container tests
> Backport changes to allow setting images for container tests

- Library/test-helpers/Dockerfile.agent
Workaround https://issues.redhat.com/browse/RHEL-7193
> Add keylime user to workaround rpm macro bug

- setup/install_upstream_rust_keylime/test.sh
Use the `testing` feature and set the TPM_BINARY_MEASUREMENTS
environment variable for the agent service when the
TPM_BINARY_MEASUREMENTS environment variable is set.
This avoids the need for modifying the code to change the location of the binary measurements log.
> install_upstream_rust_keylime: allow setting measurements location

- functional/basic-attestation-with-concatenated-certificates/main.fmf
- functional/basic-attestation-with-concatenated-certificates/test.sh
Backport from the main branch.
> Add test basic-attestation-with-concatenated-certificates

- functional/durable-attestion-sanity-on-localhost/test.sh
The current code is creating `badscript.sh` in `/` which causes troubles with repetitive execution.
> Add missing TESTDIR usage

- functional/iak-idevid-register-with-certificates/test.sh
Recommended in https://bugzilla.redhat.com/show_bug.cgi?id=2257700
> Pass -q option to wget

- Library/test-helpers/lib.sh
This function will be useful for checking non-keylime services.
> Add limeWaitForRemotePort

- upstream/run_rust_keylime_tests/test.sh
> Remove --engine llvm option for cargo tarpaulin

- regression/CVE-2023-3674/main.fmf
- regression/CVE-2023-3674/malform_attestation_record.py
- regression/CVE-2023-3674/test.sh
Backporting test from the main branch.
> Add test for CVE-2023-3674

- .tmt/dynamic_ref.fmf
- Multihost/basic-attestation/main.fmf
- Multihost/basic-attestation/payload-script/local_action_modify_payload.py
- functional/basic-attestation-on-localhost/main.fmf
- functional/basic-attestation-on-localhost/payload-script/local_action_modify_payload.py
- functional/basic-attestation-with-concatenated-certificates/main.fmf
- functional/basic-attestation-with-custom-certificates/main.fmf
- functional/basic-attestation-with-custom-certificates/payload-script/local_action_modify_payload.py
- functional/basic-attestation-with-unpriviledged-agent/main.fmf
- functional/basic-attestation-with-unpriviledged-agent/payload-script/local_action_modify_payload.py
- functional/basic-attestation-without-mtls/main.fmf
- functional/basic-attestation-without-mtls/payload-script/local_action_modify_payload.py
- functional/keylime-non-default-ports/main.fmf
- functional/keylime-non-default-ports/payload-script/local_action_modify_payload.py
- regression/issue-1380-agent-removed-and-re-added/main.fmf
- setup/enable_keylime_debug_messages/main.fmf
python3-toml is going to be deprecated
https://fedoraproject.org/wiki/Changes/DeprecatePythonToml
> Replace python3-toml with tomli or tomllib modules

- compatibility/basic-attestation-on-localhost-api-version-bump/test.sh
When running in distribution CI it may happen that keylime agent RPM version is older than the current upstream one. As a result we are not "downgrading" to an older API version. Therefore we need to use sources from SRPM file, including extra patches, so that we are working with the correct version of the source code.
> Checkout sources for the current agent version

- Library/test-helpers/lib.sh
- setup/enable_keylime_coverage/test.sh
> Code coverage fixes rhel-9-main

- Library/test-helpers/lib.sh
- setup/enable_keylime_coverage/test.sh
> Code coverage fixes rhel-10-main

- functional/iak-idevid-register-with-certificates/test.sh
This cherry picks:
- 55a403f0279a22140163e7eebdd311d22a5b4b24
- cfe787dd715e9b167d9d7a8ee165ae0cb59fb89b
- 34ecca32e3b3ba94a0a4c3994ca86f387064714d
> Cherry-pick fixes for IAK/IDevID test

- functional/iak-idevid-register-with-certificates/main.fmf
This adds dependencies that were missing in #702
> Fix IDevID/IAK test dependencies

- Library/test-helpers/lib.sh
- Multihost/basic-attestation/test.sh
- container/functional/keylime_all_in_container-basic-attestation/test.sh
- setup/configure_swtpm_device/test.sh
- setup/configure_tpm_emulator/swtpm_permissive.te
- setup/configure_tpm_emulator/test.sh
plus
- migrate the failing container test to keylime-poilicy tool
- run limeCreateTestPolicy in rlRun in a multi-host test
> Change runtime dir for swtpm

- setup/apply_workarounds/keylime_tests_workarounds.fc.fc43
Fixes broken TPM on recent Rawhide.
> Update swtpm selinux module with rawhide fixes

- Library/test-helpers/lib.sh
- setup/apply_workarounds/keylime_tests_workarounds.fc.fc43
- setup/apply_workarounds/keylime_tests_workarounds.te.fc42
- setup/apply_workarounds/keylime_tests_workarounds.te.fc43
- setup/configure_swtpm_device/test.sh
- setup/configure_tpm_emulator/swtpm_permissive.te
- setup/configure_tpm_emulator/test.sh
Cherry pick the commit b1fd5468a2b9475faa00a1d09ff18fad5a6841ff to fix the selinux AVC errors on Rawhide
EDIT: Also cherry-picked bb7598d and added workaround for new AVC
> Change swtpm runtime directory on Fedora Rawhide

- Library/test-helpers/lib.sh
At some point we need to check for keylime processes running so that we can e.g. stop them, but the current approach is doing a too broad search that it kills unrelated processes as well
As an example, if we have journalctl watching e.g. the verifier logs and we try to stop the verifier, the journalctl process would also be killed, which is not what we want.
The updated code tries to be more fine-grained and appears to do the right thing(tm).
> library: improve how lime library checks for keylime-related processes

- Library/test-helpers/ima-policy-signing
- setup/configure_kernel_ima_module/test.sh
Drop IMA_POLICY and appraisal rule. This avoids hitting kernel issue https://issues.redhat.com/browse/RHEL-104353
> remove IMA appraisal

- functional/add-agent-with-malformed-ek-cert/test.sh
In the fix attempt https://github.com/keylime/keylime/pull/1794, the cache was incorrectly added to the model object instead of the certificate object instance, meaning that the cached certificate would be used for all following certificates.
This adds a check to verify that the cached malformed certificate will not affect following certificates.
> Check that cached malformed EK cert does not affect other certs

- functional/add-agent-with-malformed-ek-cert/test.sh
In functional/add-agent-with-malformed-ek-cert test, collect both certificates separately when calling tpm2_getekcertificate.
In some systems, the tpm2_getekcertificate returns both certificates appended when called without specifying the output paths.
> Collect both RSA and ECC EK certificates with tpm2_getekcertificate
